[workspace]

members = [
    "sgtypes",
    "sgnetwork",
    "network-libp2p",
    "network-libp2p/peerset",
    "sgwallet",
    "sgwallet/local_state_storage",
    "node",
    "node/node_proto",
    "node/node_client",
    "node/node_rest_api",
    "node/node_service",
    "node/node_internal",
    "cli",
    "cli/cli_wallet",
    "sgcompiler",
    "sgchain",
    "sgstorage",
]

exclude = ["libra"]

[replace]
"libp2p:0.7.0" = { git = "https://github.com/starcoinorg/rust-libp2p", tag = "v0.7.0-stargate" }
