[rpc_config]
address = 'localhost'
port = 9001

[rest_config]
address = '127.0.0.1'
port = 7001

[net_config]
listen = '/ip4/127.0.0.1/tcp/10001'
max_sockets = 20
in_memory = false
seeds = ['/ip4/127.0.0.1/tcp/10000/p2p/80731e386aeba31813bee57882a4af64922afca7ee8ca51f8914b7405a066028']

[wallet]
chain_address = 'localhost'
chain_port = 8000
